language: cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - libcurl4-openssl-dev
  homebrew:
    taps:
      - facebook/fb
    packages:
      - buck
      - curl

os:
  - linux
  - osx

env:
  - BUCKAROO_VERSION=buckaroo-redux-alpha-8

osx_image: xcode9.3

before_install:
  - ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - ./buckaroo-client install
  - buck build -c ui.superconsole=DISABLED //:cpr
  - buck test -c ui.superconsole=DISABLED //test:get
  - buck test -c ui.superconsole=DISABLED //test:post
  - buck test -c ui.superconsole=DISABLED //test:put
  - buck test -c ui.superconsole=DISABLED //test:util
